// Copyright 2026 Maciej "juan_em (JuanX-G)" Woźniak
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Or use the bundled copy in the LICENSE file.

// Code generated by "stringer -type=ServerConfigErrorType -trimprefix=Config"; DO NOT EDIT.

package crossbow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfigErrorWorkersZero-0]
	_ = x[ConfigErrorRecoverFuncNil-1]
	_ = x[ConfigErrorMailboxSizeZero-2]
}

const _ServerConfigErrorType_name = "ErrorWorkersZeroErrorRecoverFuncNilErrorMailboxSizeZero"

var _ServerConfigErrorType_index = [...]uint8{0, 16, 35, 55}

func (i ServerConfigErrorType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ServerConfigErrorType_index)-1 {
		return "ServerConfigErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerConfigErrorType_name[_ServerConfigErrorType_index[idx]:_ServerConfigErrorType_index[idx+1]]
}
